### ISSUE TITLE
writing simple documentation on getting started with augmented reality.

### ISSUE THREAD

**Issue by VenusCh001** [SnowScriptWinterOfCode/Technical_Writing#12]
**Issue:**
Recognizing the importance of user-friendly resources, I propose the creation of straightforward documentation to assist users in getting started with augmented reality (AR).

**Objective:**
The documentation should serve as a guide for users entering the realm of augmented reality, covering fundamental aspects such as hardware requirements, software setup, and a step-by-step walkthrough to initiate their first AR experience.

kindly assign @captain-sal

**Comment by VenusCh001** [comment]
@captain-sal I want to know when will be the documentation be marked as completed

**Comment by captain-sal** [comment]
@VenusCh001, did you raise a PR?

**Comment by VenusCh001** [comment]
yes it has been merged also two weeks ago @captain-sal 
is there any problem regarding this issue ?
