### ISSUE TITLE
Writing a documentation on creating and deploying a simple web application.

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/Technical_Writing#4]
I want to add a detailed technical documentation on creating and deploying a web application.
@captain-sal kindly assign me this issue.

**Comment by bh-g** [comment]
Assigned, go for it :)

**Comment by hashcoder-deepanshi** [comment]
@bh-g please assign this to me , i would love to write a documentation on simple reactjs website
