### ISSUE TITLE
Documentation on CSS Flexbox and Grid Layout.

### ISSUE THREAD

**Issue by Riddhi050803** [SnowScriptWinterOfCode/Technical_Writing#5]

**Comment by Riddhi050803** [comment]
Really wanted to do this. Please assign this to me.

**Comment by preetijangra15** [comment]
please assign this to me'

**Comment by priyamina** [comment]
@captain-sal  please assign this issue to me, i want to add documentation with attractive images ,code snippets,with explanation of every topic in-depth.I would be really thankful.
