### ISSUE TITLE
DSA technical Paper on Linked List 

### ISSUE THREAD

**Issue by NEGRAH-S** [SnowScriptWinterOfCode/Technical_Writing#6]
@Nitya-Pasrija , I want to write a paper on Linked List as part of DSA-technical Writing , it will inlcude : 
- Type of linked list 
- Difference in various type of Linked List 
-  Approach 
- Working 
- Algo (if)
- Flowchart 

Kindly assign it to me

**Comment by hashcoder-deepanshi** [comment]
@bh-g can i work on this as well . Please assign it to me.

**Comment by NEGRAH-S** [comment]
Thanks @captain-sal
