### ISSUE TITLE
Document on AI-ML

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/Technical_Writing#62]
It involves the application of advanced computational and mathematical techniques to create intelligent systems and perform tasks by making informed decisions. Since it is a growing field ,

Please assign it to me @captain-sal @bh-g

**Comment by Gurn-k** [comment]
please assign this issue to me also @captain-sal

**Comment by Gurn-k** [comment]
hello,please review and merge my pr #67
